# Generated by Django 5.0.6 on 2024-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
