# Generated by Django 5.0.6 on 2024-07-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forum_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='anonimo',
        ),
    ]
