# Generated by Django 5.0.6 on 2024-08-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_alter_aluno_user'),
        ('forum', '0004_remove_forum_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.aluno'),
        ),
    ]
