# Generated by Django 5.0.6 on 2025-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_respondertopico_categoria_forum_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
