# Generated by Django 5.0.6 on 2025-08-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_forum_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondertopico',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.forum'),
        ),
    ]
