# Generated by Django 5.0.6 on 2025-08-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_respondertopico_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='resposta_destaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_destaque', to='forum.respondertopico'),
        ),
    ]
