# Generated by Django 5.0.6 on 2024-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='tempo_resolucao',
            field=models.DurationField(default='0:00:00'),
        ),
    ]
