# Generated by Django 5.0.6 on 2024-08-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0002_alter_desempenho_tempo_resolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='tempo_resolucao',
        ),
    ]
