# Generated by Django 5.0.6 on 2024-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0003_remove_desempenho_tempo_resolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='pontuacaoAluno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
