# Generated by Django 5.0.6 on 2024-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0004_alter_desempenho_pontuacaoaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
    ]
