# Generated by Django 5.0.6 on 2024-07-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoPdf',
            fields=[
                ('materialapoio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materialApoio.materialapoio')),
                ('arquivo', models.FileField(upload_to='pdfs/')),
            ],
            bases=('materialApoio.materialapoio',),
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('materialapoio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materialApoio.materialapoio')),
                ('link_youtube', models.URLField()),
            ],
            bases=('materialApoio.materialapoio',),
        ),
    ]
