# Generated by Django 5.0.6 on 2024-08-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('material_apoio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_pdf', to='materialApoio.materialapoio')),
            ],
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_youtube', models.URLField()),
                ('material_apoio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_youtube', to='materialApoio.materialapoio')),
            ],
        ),
    ]
