# Generated by Django 5.0.6 on 2024-08-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialApoio', '0003_alter_arquivopdf_material_apoio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaMental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapaMental', models.ImageField(blank=True, null=True, upload_to='mapas_mentais/')),
                ('material_apoio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mapa_mental', to='materialApoio.materialapoio')),
            ],
        ),
    ]
