# Generated by Django 5.0.6 on 2024-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialApoio', '0004_mapamental'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='quantidade_conteudo',
            field=models.IntegerField(default=0),
        ),
    ]
