# Generated by Django 5.0.6 on 2024-09-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialApoio', '0006_remove_arquivopdf_mapamental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapamental',
            name='material_apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_mentais', to='materialApoio.materialapoio'),
        ),
    ]
