# Generated by Django 5.0.6 on 2024-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialApoio', '0007_alter_mapamental_material_apoio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialapoio',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
