# Generated by Django 5.0.6 on 2025-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialApoio', '0008_materialapoio_visualizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapamental',
            old_name='mapaMental',
            new_name='mapa_mental',
        ),
        migrations.AddField(
            model_name='arquivopdf',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivopdf',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=150),
        ),
        migrations.AddField(
            model_name='mapamental',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapamental',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=150),
        ),
        migrations.AddField(
            model_name='videoyoutube',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoyoutube',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=150),
        ),
        migrations.AlterField(
            model_name='materialapoio',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=150),
        ),
    ]
