# Generated by Django 5.0.6 on 2024-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codicoTurma', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
