# Generated by Django 5.0.6 on 2024-07-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_turma_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
    ]
