# Generated by Django 5.0.6 on 2024-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_remove_turma_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codicoTurma',
            field=models.CharField(default='12345', max_length=10, unique=True),
        ),
    ]
