# Generated by Django 5.0.6 on 2024-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilador',
            name='resultado_execucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
