# Generated by Django 5.0.6 on 2024-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0003_rename_codico_compilador_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilador',
            old_name='codigo',
            new_name='codigo_c',
        ),
        migrations.AddField(
            model_name='compilador',
            name='entradas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='compilador',
            name='resultado_execucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
