# Generated by Django 5.0.6 on 2024-07-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0004_rename_codigo_compilador_codigo_c_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compilador',
        ),
    ]
