# Generated by Django 5.0.6 on 2024-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicio', '0005_delete_compilador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'Náo Respondido'), ('R', 'Respondido')], default='N', max_length=1)),
                ('numeroDoExercico', models.PositiveIntegerField()),
            ],
        ),
    ]
