# Generated by Django 5.0.6 on 2024-08-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
    ]
