# Generated by Django 5.0.6 on 2024-08-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0008_alter_aluno_user'),
        ('exercicio', '0007_delete_exercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscricaoDetalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'Não Respondido'), ('R', 'Respondido')], default='N', max_length=1)),
                ('numeroDoExercicio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDica', models.PositiveIntegerField()),
                ('conteudoDica', models.TextField()),
                ('imagemExemplo', models.ImageField(blank=True, null=True, upload_to='imagemProblema/')),
            ],
        ),
        migrations.CreateModel(
            name='Sintaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('numeroExercicio', models.PositiveIntegerField(unique=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', max_length=1)),
                ('totalExercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDoExercicio', models.TextField()),
                ('resultado', models.TextField()),
                ('pontuacao', models.PositiveIntegerField()),
                ('dataEnvio', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='DicaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoApoio', models.TextField()),
                ('descricaoDetalhada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.discricaodetalhada')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.exercicio')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.problema')),
                ('sintaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.sintaxe')),
            ],
        ),
    ]
