# Generated by Django 5.0.6 on 2024-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0010_listaexercicio_saidaesperada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaexercicio',
            name='saidaEsperada',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='entradaExemplo',
            field=models.TextField(default=''),
        ),
    ]
