# Generated by Django 5.0.6 on 2024-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0011_remove_listaexercicio_saidaesperada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='saidaExemplo',
            field=models.TextField(default=''),
        ),
    ]
