# Generated by Django 5.0.6 on 2024-08-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0013_alter_exercicio_entradaexemplo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaexercicio',
            name='totalExercicio',
        ),
        migrations.AddField(
            model_name='listaexercicio',
            name='totalExercicio',
            field=models.ManyToManyField(to='exercicio.exercicio'),
        ),
    ]
