# Generated by Django 5.0.6 on 2024-08-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0015_remove_listaexercicio_totalexercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='lista_exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicio.listaexercicio'),
        ),
    ]
