# Generated by Django 5.0.6 on 2024-08-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0016_exercicio_lista_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='lista_exercicio',
        ),
        migrations.AddField(
            model_name='listaexercicio',
            name='exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicio.exercicio'),
        ),
    ]
