# Generated by Django 5.0.6 on 2024-08-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0017_remove_exercicio_lista_exercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaexercicio',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='listaexercicio',
            name='exercicio',
            field=models.ManyToManyField(blank=True, to='exercicio.exercicio'),
        ),
    ]
