# Generated by Django 5.0.6 on 2024-08-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0018_remove_listaexercicio_exercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaexercicio',
            name='exercicio',
            field=models.ManyToManyField(blank=True, null=True, to='exercicio.exercicio'),
        ),
    ]
