# Generated by Django 5.0.6 on 2024-08-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0019_alter_listaexercicio_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaexercicio',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='listaexercicio',
            name='totalExercicio',
            field=models.ManyToManyField(to='exercicio.exercicio'),
        ),
        migrations.AlterField(
            model_name='listaexercicio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
