# Generated by Django 5.0.6 on 2024-08-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0020_remove_listaexercicio_exercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaexercicio',
            name='totalExercicio',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='lista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicio.listaexercicio'),
        ),
    ]
