# Generated by Django 5.0.6 on 2024-08-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0021_remove_listaexercicio_totalexercicio_exercicio_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='lista',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicio.listaexercicio'),
        ),
    ]
