# Generated by Django 5.0.6 on 2024-08-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0022_alter_exercicio_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaexercicio',
            name='toltaExcercicios',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
