# Generated by Django 5.0.6 on 2024-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0023_listaexercicio_toltaexcercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaexercicio',
            name='dificuldade',
            field=models.CharField(choices=[('FM', 'Fácil e Média'), ('MD', 'Médio e Difícil ')], default='FM', max_length=2),
        ),
        migrations.AlterField(
            model_name='listaexercicio',
            name='status',
            field=models.BooleanField(choices=[('FM', 'Fácil e Média'), ('MD', 'Médio e Difícil ')], default='FM', max_length=2),
        ),
    ]
