# Generated by Django 5.0.6 on 2024-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0024_alter_listaexercicio_dificuldade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaexercicio',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível')], default='D', max_length=1),
        ),
    ]
