# Generated by Django 5.0.6 on 2024-06-20 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nomeAluno', models.CharField(max_length=100)),
                ('institucao', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='A matrícula deve conter apenas números.', regex='^\\d+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
