# Generated by Django 5.0.6 on 2024-07-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma')),
            ],
        ),
    ]
