# Generated by Django 5.0.6 on 2024-07-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_aluno_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='institucao',
            new_name='instituicao',
        ),
    ]
