# Generated by Django 5.0.6 on 2024-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_institucao_aluno_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
