# Generated by Django 5.0.6 on 2024-08-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0009_aluno_exercicio_respondido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloEmblema', models.CharField(max_length=100)),
                ('subtituloEmblema', models.CharField(default='', max_length=250)),
                ('codigoEmblema', models.CharField(max_length=10)),
                ('imagemEmblema', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('criterio', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('desbloqueado', 'Desbloqueado'), ('nao_desbloqueado', 'Não Desbloqueado')], default='nao_desbloqueado', max_length=20)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emblema', to='contas.aluno')),
            ],
        ),
    ]
