# Generated by Django 5.0.6 on 2024-08-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0008_alter_aluno_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmblema', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagemEmblema', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('criterio', models.CharField(max_length=255)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emblema', to='contas.aluno')),
            ],
        ),
    ]
