# Generated by Django 5.0.6 on 2024-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emblemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emblema',
            old_name='nomeEmblema',
            new_name='tituloEmblema',
        ),
        migrations.AddField(
            model_name='emblema',
            name='subtiluloEmblema',
            field=models.CharField(default='', max_length=250),
        ),
    ]
