# Generated by Django 5.0.6 on 2024-08-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emblemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emblema',
            name='codigoEmblema',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
