# Generated by Django 5.0.6 on 2024-09-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_aluno_exercicio_respondido'),
        ('emblemas', '0002_alter_emblema_codigoemblema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emblema',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emblemas', to='contas.aluno'),
        ),
    ]
