# Generated by Django 5.0.6 on 2024-07-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0003_alter_perfil_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('duvidaAluno', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status_respsota', models.BooleanField(default=False)),
                ('tematica', models.CharField(max_length=200)),
                ('anonimo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
            ],
        ),
    ]
