# Generated by Django 5.0.6 on 2024-08-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duvidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duvidas',
            old_name='status_respsota',
            new_name='status_resposta',
        ),
    ]
